.github/workflows/coverage.yml, .github/workflows/typo.yml, CHANGELOG.md, fastrace/src/collector/mod.rs, fastrace/src/macros.rs
=> chore: Fix CI

CHANGELOG.md, fastrace-datadog/Cargo.toml, fastrace-futures/Cargo.toml, fastrace-macro/Cargo.toml, fastrace-opentelemetry/Cargo.toml, fastrace-opentelemetry/src/lib.rs, fastrace/Cargo.toml, test-statically-disable/Cargo.toml
We may need a 0.6.9 or 0.7.0 release.
=> build(deps): opentelemetry and more

CHANGELOG.md, fastrace/src/collector/mod.rs, fastrace/src/lib.rs
=> chore!: remove deprecated methods

CHANGELOG.md, README.md, fastrace-macro/src/lib.rs, fastrace/examples/unit_test.rs, fastrace/src/future.rs, fastrace/src/lib.rs, fastrace/src/macros.rs
Closes https://github.com/fastracelabs/fastrace/issues/10
=> feat: rename full_name to func_path

.editorconfig, .github/workflows/ci.yml, Cargo.toml, README.md, fastrace-datadog/Cargo.toml, fastrace-futures/Cargo.toml, fastrace-jaeger/Cargo.toml, fastrace-macro/Cargo.toml, fastrace-opentelemetry/Cargo.toml, fastrace/Cargo.toml, test-statically-disable/Cargo.toml
This closes https://github.com/fastracelabs/fastrace/issues/15
=> build: release crates separatedly

Cargo.toml, README.md, fastrace-datadog/Cargo.toml, fastrace-futures/Cargo.toml, fastrace-jaeger/Cargo.toml, fastrace-macro/Cargo.toml, fastrace-opentelemetry/Cargo.toml, fastrace/Cargo.toml, test-statically-disable/Cargo.toml
=> chore: drop the effectively deprecated author meta field

fastrace-opentelemetry/Cargo.toml, fastrace/Cargo.toml
Bump otel deps to 0.26.
close #44
=> chore: bump otel deps

fastrace-futures/Cargo.toml, fastrace-futures/src/lib.rs, fastrace-opentelemetry/Cargo.toml, fastrace/Cargo.toml, fastrace/src/collector/global_collector.rs, fastrace/src/local/local_collector.rs, fastrace/src/local/raw_span.rs, fastrace/src/local/span_queue.rs, fastrace/src/span.rs
=> chore: update dependencies

README.md
This PR adds a libs.tech recommendation badge to the README, highlighting this project as a top choice in its category.
Since [**your project has been approved and listed**](https://libs.tech/project/829370199/fastrace) among high-quality, curated projects, you can confidently display his endorsement badge.
[![libs.tech recommends](https://libs.tech/project/829370199/badge.svg)](https://libs.tech/project/829370199/fastrace)
Well done!
=> chore: add a Recommendation Badge from libs.tech

fastrace/src/local/local_span_line.rs
Closes https://github.com/fast/fastrace/issues/89
=> fix: capture sampled for local context

Cargo.lock, Cargo.toml, fastrace-opentelemetry/CHANGELOG.md, fastrace-opentelemetry/Cargo.toml, fastrace/Cargo.toml
Wait on https://github.com/tokio-rs/tracing-opentelemetry/pull/205/
=> chore: opentelemetry 0.30.0

fastrace/src/collector/id.rs, fastrace/src/local/local_collector.rs, fastrace/src/span.rs, fastrace/tests/lib.rs
Partially address https://github.com/fast/fastrace/issues/92
=> fix: ignore invalid w3c traceparent

README.md, fastrace/src/span.rs
Closes https://github.com/fast/fastrace/issues/99
=> perf: don't submit if not sampled

CHANGELOG.md, Cargo.toml, fastrace/Cargo.toml, fastrace/src/collector/global_collector.rs, fastrace/src/collector/mod.rs, fastrace/src/macros.rs, fastrace/src/span.rs, fastrace/tests/lib.rs, tests/statically-disable/src/main.rs
Closes https://github.com/fast/fastrace/issues/100
=> chore: rename Config::cancelable to tail_sampled

fastrace-macro/Cargo.toml, fastrace-macro/src/lib.rs, fastrace/Cargo.toml, fastrace/src/collector/mod.rs
Resolves https://github.com/fast/fastrace/issues/102
Related https://github.com/fast/fastrace/pull/91
=> feat: do not expand macro if not enabled

fastrace-macro/src/lib.rs, tests/macros/tests/ui/ok/has-crate-path.rs
Resolves https://github.com/fast/fastrace/issues/69
=> feat: add crate attribute to trace macro

CHANGELOG.md, Cargo.lock, Cargo.toml, fastrace-datadog/Cargo.toml, fastrace-futures/Cargo.toml, fastrace-jaeger/Cargo.toml, fastrace-macro/Cargo.toml, fastrace/Cargo.toml
Closes https://github.com/fast/fastrace/issues/98
=> chore: bump 0.7.10

Cargo.lock, examples/asynchronous.rs, examples/synchronous.rs, fastrace-opentelemetry/CHANGELOG.md, fastrace-opentelemetry/Cargo.toml, fastrace-opentelemetry/README.md, fastrace-opentelemetry/src/lib.rs, fastrace/benches/compare.rs
Resolves https://github.com/fast/fastrace/issues/85
=> feat: detect span kind from properties

Cargo.lock, Cargo.toml, fastrace-datadog/Cargo.toml, fastrace-futures/Cargo.toml, fastrace-jaeger/Cargo.toml, fastrace-macro/Cargo.toml, fastrace/Cargo.toml, fastrace/src/collector/id.rs, fastrace/src/local/local_collector.rs, fastrace/src/span.rs, fastrace/src/util/tree.rs, fastrace/tests/lib.rs
Resolves https://github.com/fast/fastrace/issues/115
=> fix: SpanContext::random() should set span id as zero

CHANGELOG.md, fastrace/src/collector/global_collector.rs, fastrace/src/collector/id.rs
Closes https://github.com/fast/fastrace/issues/119
=> fix: memory leak when reporter is not set
